name = "sns-article-publisher"
main = "src/index.ts"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
routes = [
    { pattern = "api.maretol.xyz/sns-publisher", zone_name = "maretol.xyz" }
]

[images]
binding = "IMAGES"

[dev]
port = 30254

[env.staging]
name = "sns-article-publisher-stg"
routes = [
    { "pattern" = "dev-api.maretol.xyz/sns-publisher", zone_name = "maretol.xyz" }
]

[observability]
enabled = true
