name = "cms-cache-purger"
main = "src/index.ts"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
routes = [
    { pattern = "api.maretol.xyz/cms-webhook", zone_name = "maretol.xyz" }
]
kv_namespaces = [
    { binding = "CMS_CACHE", id = "eda084a77bf54fab906cd6b02fa1b3a1" }
]

[dev]
port = 30223

[env.staging]
name = "cms-cache-purger-stg"
routes = [
    { "pattern" = "dev-api.maretol.xyz/cms-webhook", zone_name = "maretol.xyz" }
]
kv_namespaces = [
    { binding = "CMS_CACHE", id = "eda084a77bf54fab906cd6b02fa1b3a1" }
]

[observability]
enabled = true
