name = "maretol-base-v3"
main = ".open-next/worker.js"
compatibility_date = "2025-05-05"
compatibility_flags = [ "nodejs_compat", "global_fetch_strictly_public" ]

routes = [
    { pattern = "www.maretol.xyz", custom_domain = true }
]
services = [
    { binding = "OGP_FETCHER", service = "ogp-data-fetcher", environment = "production" },
    { binding = "CMS_FETCHER", service = "cms-data-fetcher", environment = "production" },
    { binding = "OGP_RPC", service = "ogp-data-fetcher", environment = "production" },
    { binding = "CMS_RPC", service = "cms-data-fetcher", environment = "production" },
]
kv_namespaces = [
    { binding = "OGP_FETCHER_CACHE", id = "e04820b5b32b4a8f9b45ecef847bcbb0"},
    { binding = "CMS_CACHE", id = "eda084a77bf54fab906cd6b02fa1b3a1"},
    { binding = "IMAGE_CACHE", id = "e5a68d1f3fca4af2975762a3ce235475"}
]
secrets_store_secrets = [
    { binding="CLARITY_ID", store_id="da1dbdf4b4e24ed3b82c0d8e117f09d4", secret_name="CLARITY_ID" },
    { binding="AXIOM_ENDPOINT", store_id="da1dbdf4b4e24ed3b82c0d8e117f09d4", secret_name="AXIOM_ENDPOINT" },
    { binding="AXIOM_APITOKEN", store_id="da1dbdf4b4e24ed3b82c0d8e117f09d4", secret_name="AXIOM_APITOKEN" }
]

[dev]
port = 9593

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[vars]
HOST = "https://www.maretol.xyz"
ENV = "PRD"

[env.staging.vars]
HOST = "https://maretol-base-v3-stg.maretol-ruha.workers.dev"
ENV = "STG"

[env.staging]
name = "maretol-base-v3-stg"
routes = [
]
workers_dev = true
services = [
    { binding = "OGP_FETCHER", service = "ogp-data-fetcher-stg", environment = "production" },
    { binding = "CMS_FETCHER", service = "cms-data-fetcher-stg", environment = "production" },
    { binding = "OGP_RPC", service = "ogp-data-fetcher-stg", environment = "production" },
    { binding = "CMS_RPC", service = "cms-data-fetcher-stg", environment = "production", entrypoint = "CMSDataFetcher" },
]
kv_namespaces = [
    { binding = "OGP_FETCHER_CACHE", id = "e04820b5b32b4a8f9b45ecef847bcbb0"},
    { binding = "CMS_CACHE", id = "eda084a77bf54fab906cd6b02fa1b3a1"},
    { binding = "IMAGE_CACHE", id = "e5a68d1f3fca4af2975762a3ce235475"}
]
secrets_store_secrets = [
    { binding="CLARITY_ID", store_id="da1dbdf4b4e24ed3b82c0d8e117f09d4", secret_name="CLARITY_ID" },
    { binding="AXIOM_ENDPOINT", store_id="da1dbdf4b4e24ed3b82c0d8e117f09d4", secret_name="AXIOM_ENDPOINT" },
    { binding="AXIOM_APITOKEN", store_id="da1dbdf4b4e24ed3b82c0d8e117f09d4", secret_name="AXIOM_APITOKEN" }
]