#:schema node_modules/wrangler/config-schema.json
name = "ogp-data-fetcher"
main = "src/index.ts"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
routes = [
#     { pattern = "api.maretol.xyz", custom_domain = true }, # ドメインはCMSの方優先でやる
    { pattern = "api.maretol.xyz/ogp*", zone_name = "maretol.xyz" }
]

[dev]
port = 45678

[observability]
enabled = true

[env.staging]
name = "ogp-data-fetcher-stg"
routes = [
#     { pattern = "dev-api.maretol.xyz", custom_domain = true }, # ドメインはCMSの方優先でやる
    { pattern = "dev-api.maretol.xyz/ogp*", zone_name = "maretol.xyz" }
]