#:schema node_modules/wrangler/config-schema.json
name = "ogp-data-fetcher"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 45678

[env.staging]
name = "ogp-data-fetcher-stg"
