# pages の dependabot はバージョン更新後に npm install をしてあげないと package-lock.json との統合性が取れなくなるっぽいのでそれをする

name: npm install after dependabot

on:
  pull_request:
    branches:
      - pre-development
    paths:
      - 'pages/**'

env:
  NODE_VERSION: 20.16.0

permissions:
  contents: write

jobs:
  npm-install:
    runs-on: ubuntu-latest
    environment:
      name: bot
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        run: npm install

      - name: commit and push
        run: |
          git config user.name "maretol-bot"
          git config user.email "maretol+bot@users.noreply.github.com"
          git add .
          git commit -m "[bot]chore(deps): update dependencies"
          git push
